// <auto-generated />

namespace BiliCopilot.UI.Models.Constants;

public enum StringNames
{
    /// <summary>
    /// 操作中止
    /// </summary>
    Aborted,

    /// <summary>
    /// 关于
    /// </summary>
    About,

    /// <summary>
    /// 关于此应用
    /// </summary>
    AboutThisApp,

    /// <summary>
    /// 添加
    /// </summary>
    Add,

    /// <summary>
    /// 添加评论失败，请稍后再试
    /// </summary>
    AddReplyFailed,

    /// <summary>
    /// 添加到稍后再看
    /// </summary>
    AddToViewLater,

    /// <summary>
    /// 添加稍后再看失败
    /// </summary>
    AddViewLaterFailed,

    /// <summary>
    /// 已添加到稍后再看列表
    /// </summary>
    AddViewLaterSucceed,

    /// <summary>
    /// 高级选项
    /// </summary>
    AdvancedOptions,

    /// <summary>
    /// 别名
    /// </summary>
    Alias,

    /// <summary>
    /// 全部动态
    /// </summary>
    AllDynamic,

    /// <summary>
    /// 同时点赞
    /// </summary>
    AlsoLike,

    /// <summary>
    /// 动漫
    /// </summary>
    Anime,

    /// <summary>
    /// 任意
    /// </summary>
    Any,

    /// <summary>
    /// 探索视频应用桌面交互的新可能
    /// </summary>
    AppDescription,

    /// <summary>
    /// 哔哩助理
    /// </summary>
    AppName,

    /// <summary>
    /// 应用程序主题
    /// </summary>
    AppTheme,

    /// <summary>
    /// 选择要显示的应用主题
    /// </summary>
    AppThemeDescription,

    /// <summary>
    /// 应用提示
    /// </summary>
    AppTip,

    /// <summary>
    /// 文章
    /// </summary>
    Article,

    /// <summary>
    /// 文章阅读 - {0}
    /// </summary>
    ArticleReader,

    /// <summary>
    /// 至少应选择一个分P
    /// </summary>
    AtLeastChooseOnePart,

    /// <summary>
    /// @我的
    /// </summary>
    AtMe,

    /// <summary>
    /// 在{0}中@了我
    /// </summary>
    AtMessageTypeDescription,

    /// <summary>
    /// 观众反馈
    /// </summary>
    AudienceFeedback,

    /// <summary>
    /// 音频通道数
    /// </summary>
    AudioChannels,

    /// <summary>
    /// 音频编解码器
    /// </summary>
    AudioCodec,

    /// <summary>
    /// 音频采样格式
    /// </summary>
    AudioSampleFormat,

    /// <summary>
    /// 音频采样率
    /// </summary>
    AudioSampleRate,

    /// <summary>
    /// 音频源地址
    /// </summary>
    AudioSourceUrl,

    /// <summary>
    /// 音频播放地址
    /// </summary>
    AudioUrl,

    /// <summary>
    /// {0} 发布
    /// </summary>
    AuthorPublishTime,

    /// <summary>
    /// 自动关闭当前播放窗口
    /// </summary>
    AutoClosePlayerWindow,

    /// <summary>
    /// 当前播放窗口即将关闭，您可以关闭此提示以保留窗口
    /// </summary>
    AutoClosePlayerWindowDescription,

    /// <summary>
    /// 播放结束后自动关闭视频
    /// </summary>
    AutoCloseWindowWhenEnded,

    /// <summary>
    /// 在视频播放结束后，如果没有连续播放和关联播放任务，则自动关闭视频播放窗口
    /// </summary>
    AutoCloseWindowWhenEndedDescription,

    /// <summary>
    /// 加载后自动跳转上次播放进度
    /// </summary>
    AutoLoadHistoryWhenLoaded,

    /// <summary>
    /// 自动
    /// </summary>
    Automatic,

    /// <summary>
    /// 自动播放关联视频
    /// </summary>
    AutoNextRelatedVideo,

    /// <summary>
    /// 在视频播放结束后，如果有关联视频，则在 5 秒倒计时结束后自动播放下一个视频
    /// </summary>
    AutoNextRelatedVideoDescription,

    /// <summary>
    /// 加载完成后自动播放
    /// </summary>
    AutoPlayWhenLoaded,

    /// <summary>
    /// AV1
    /// </summary>
    Av1,

    /// <summary>
    /// AV/BV 互转
    /// </summary>
    AvBvConverter,

    /// <summary>
    /// 视频AV号与BV号相互转换
    /// </summary>
    AvBvConverterDescription,

    /// <summary>
    /// 应用将根据输入的 Id 自动判断输入的是 AV 号还是 BV 号。
    /// </summary>
    AvBvConverterIntroduce,

    /// <summary>
    /// AV或BV号
    /// </summary>
    AvBvId,

    /// <summary>
    /// 返回
    /// </summary>
    Back,

    /// <summary>
    /// 后退
    /// </summary>
    BackSkip,

    /// <summary>
    /// 返回标准视图
    /// </summary>
    BackToDefaultView,

    /// <summary>
    /// 返回主页
    /// </summary>
    BackToHome,

    /// <summary>
    /// 返回上一级
    /// </summary>
    BackToPrevious,

    /// <summary>
    /// 返回互动视频开头
    /// </summary>
    BackToStart,

    /// <summary>
    /// 番剧
    /// </summary>
    Bangumi,

    /// <summary>
    /// 点赞数
    /// </summary>
    BeLikeCount,

    /// <summary>
    /// 开发者B站主页
    /// </summary>
    BiliHomePage,

    /// <summary>
    /// 亿
    /// </summary>
    Billion,

    /// <summary>
    /// 比特率
    /// </summary>
    Bitrate,

    /// <summary>
    /// 青色
    /// </summary>
    Blue,

    /// <summary>
    /// 底部
    /// </summary>
    Bottom,

    /// <summary>
    /// 底部
    /// </summary>
    BottomDanmaku,

    /// <summary>
    /// 显示底部进度条
    /// </summary>
    BottomProgressVisible,

    /// <summary>
    /// 播放视频时在底部显示当前播放进度
    /// </summary>
    BottomProgressVisibleDescription,

    /// <summary>
    /// 已清理缓存
    /// </summary>
    CacheCleared,

    /// <summary>
    /// 取消
    /// </summary>
    Cancel,

    /// <summary>
    /// 验证码
    /// </summary>
    Captcha,

    /// <summary>
    /// 请输入右侧验证码
    /// </summary>
    CaptchaHolder,

    /// <summary>
    /// 验证码不能为空
    /// </summary>
    CaptchaIsEmpty,

    /// <summary>
    /// 演职人员
    /// </summary>
    CastAndCrew,

    /// <summary>
    /// 聊天互动
    /// </summary>
    Chat,

    /// <summary>
    /// 聊天列表
    /// </summary>
    ChatList,

    /// <summary>
    /// 请输入聊天消息
    /// </summary>
    ChatMessagePlaceholderText,

    /// <summary>
    /// 验证
    /// </summary>
    Check,

    /// <summary>
    /// 验证网页登录
    /// </summary>
    CheckWebSignIn,

    /// <summary>
    /// 子分区
    /// </summary>
    ChildPartition,

    /// <summary>
    /// 打算投几个币？
    /// </summary>
    ChooseCoinNumber,

    /// <summary>
    /// 选择下载文件夹
    /// </summary>
    ChooseDownloadFolder,

    /// <summary>
    /// 选择收藏夹
    /// </summary>
    ChooseFavorite,

    /// <summary>
    /// 影视
    /// </summary>
    Cinema,

    /// <summary>
    /// 清除
    /// </summary>
    Clean,

    /// <summary>
    /// 清除日志记录
    /// </summary>
    CleanLogger,

    /// <summary>
    /// 清除
    /// </summary>
    Clear,

    /// <summary>
    /// 清除缓存
    /// </summary>
    ClearCache,

    /// <summary>
    /// 清理本地的图片缓存以减少应用数据占用
    /// </summary>
    ClearCacheDescription,

    /// <summary>
    /// 清空历史记录
    /// </summary>
    ClearHistory,

    /// <summary>
    /// 是否要清空当前所选分区的历史记录？
    /// </summary>
    ClearHistoryWarning,

    /// <summary>
    /// 清空稍后再看
    /// </summary>
    ClearViewLater,

    /// <summary>
    /// 是否要清空稍后再看列表？
    /// </summary>
    ClearViewLaterWarning,

    /// <summary>
    /// 关闭
    /// </summary>
    Close,

    /// <summary>
    /// 立即关闭
    /// </summary>
    CloseNow,

    /// <summary>
    /// 投币
    /// </summary>
    Coin,

    /// <summary>
    /// 硬币数
    /// </summary>
    CoinCount,

    /// <summary>
    /// 投币失败，试试看只投一个吧
    /// </summary>
    CoinFailed,

    /// <summary>
    /// 原创视频方可投2个币
    /// </summary>
    CoinNumberTip,

    /// <summary>
    /// 投个币赞赏一下 UP 主的劳动成果吧！
    /// </summary>
    CoinTip,

    /// <summary>
    /// 收藏时间
    /// </summary>
    CollectTime,

    /// <summary>
    /// 颜色
    /// </summary>
    Color,

    /// <summary>
    /// 色域
    /// </summary>
    ColorSpace,

    /// <summary>
    /// 评论列表
    /// </summary>
    Comments,

    /// <summary>
    /// 小窗模式
    /// </summary>
    CompactOverlayMode,

    /// <summary>
    /// 综合
    /// </summary>
    Comprehensive,

    /// <summary>
    /// 综合动态
    /// </summary>
    ComprehensiveDynamics,

    /// <summary>
    /// 配置名称
    /// </summary>
    ConfigName,

    /// <summary>
    /// 确认
    /// </summary>
    Confirm,

    /// <summary>
    /// 内容
    /// </summary>
    Content,

    /// <summary>
    /// 上次应用关闭时您仍在播放视频，你可以继续播放该视频：
    /// </summary>
    ContinuePlayDescription,

    /// <summary>
    /// 是否继续播放？
    /// </summary>
    ContinuePlayTitle,

    /// <summary>
    /// 继续观看
    /// </summary>
    ContinuePreviousView,

    /// <summary>
    /// 连续播放
    /// </summary>
    ContinuousPlay,

    /// <summary>
    /// 当视频有多个分集时自动连续播放（一集结束自动切换到下一集）
    /// </summary>
    ContinuousPlayDescription,

    /// <summary>
    /// 转换
    /// </summary>
    Convert,

    /// <summary>
    /// 已复制
    /// </summary>
    Copied,

    /// <summary>
    /// 复制 DASH 内容
    /// </summary>
    CopyDashContent,

    /// <summary>
    /// © {0} Richasy。GPL 开源许可。
    /// </summary>
    Copyright,

    /// <summary>
    /// 复制到剪切板
    /// </summary>
    CopyToClipboard,

    /// <summary>
    /// 截图后复制到剪切板
    /// </summary>
    CopyToClipboardAfterScreenshot,

    /// <summary>
    /// 复制视频网址
    /// </summary>
    CopyVideoUrl,

    /// <summary>
    /// 封面下载
    /// </summary>
    CoverDownloader,

    /// <summary>
    /// 下载指定视频的封面到本地文件
    /// </summary>
    CoverDownloaderDescription,

    /// <summary>
    /// 输入视频的 AV 或 BV 号，应用会尝试获取其封面并提供预览，确认后请点击下载按钮，应用会将其下载到图库并打开
    /// </summary>
    CoverDownloaderIntroduce,

    /// <summary>
    /// 创建配置
    /// </summary>
    CreateConfig,

    /// <summary>
    /// 当前播放速率
    /// </summary>
    CurrentPlaybackRate,

    /// <summary>
    /// 当前进度
    /// </summary>
    CurrentProgress,

    /// <summary>
    /// 当前音量
    /// </summary>
    CurrentVolume,

    /// <summary>
    /// 当前服务
    /// </summary>
    CurrentWebDavService,

    /// <summary>
    /// 弹幕
    /// </summary>
    Danmaku,

    /// <summary>
    /// 弹幕显示区域
    /// </summary>
    DanmakuArea,

    /// <summary>
    /// 自动限制同屏弹幕数
    /// </summary>
    DanmakuAutoLimit,

    /// <summary>
    /// 弹幕加粗
    /// </summary>
    DanmakuBold,

    /// <summary>
    /// 弹幕数
    /// </summary>
    DanmakuCount,

    /// <summary>
    /// 同屏弹幕密度
    /// </summary>
    DanmakuDensity,

    /// <summary>
    /// 弹幕显示设置
    /// </summary>
    DanmakuDisplaySettings,

    /// <summary>
    /// 弹幕字体
    /// </summary>
    DanmakuFont,

    /// <summary>
    /// 弹幕大小
    /// </summary>
    DanmakuFontSize,

    /// <summary>
    /// 弹幕合并
    /// </summary>
    DanmakuMerge,

    /// <summary>
    /// 弹幕不透明度
    /// </summary>
    DanmakuOpacity,

    /// <summary>
    /// 发个友善的弹幕见证当下
    /// </summary>
    DanmakuPlaceholder,

    /// <summary>
    /// 弹幕发送设置
    /// </summary>
    DanmakuSendSettings,

    /// <summary>
    /// 弹幕速度
    /// </summary>
    DanmakuSpeed,

    /// <summary>
    /// 弹幕样式
    /// </summary>
    DanmakuStyle,

    /// <summary>
    /// 弹幕开关
    /// </summary>
    DanmakuSwitch,

    /// <summary>
    /// 弹幕缩放
    /// </summary>
    DanmakuZoom,

    /// <summary>
    /// 深色
    /// </summary>
    DarkTheme,

    /// <summary>
    /// 数据分析
    /// </summary>
    DataAnalysis,

    /// <summary>
    /// 应用会采集一些使用数据（不包含隐私信息）用以进行功能分析，您使用本软件将被视作同意采集数据
    /// </summary>
    DataCollectWarning,

    /// <summary>
    /// 数据使用
    /// </summary>
    DataUsage,

    /// <summary>
    /// 调试信息
    /// </summary>
    DebugInformation,

    /// <summary>
    /// 解码类型
    /// </summary>
    DecodeType,

    /// <summary>
    /// 选择视频的解码方式，可以选择强制硬解或软解
    /// </summary>
    DecodeTypeDescription,

    /// <summary>
    /// 解码失败或者正在切换片源
    /// </summary>
    DecodingError,

    /// <summary>
    /// 默认
    /// </summary>
    Default,

    /// <summary>
    /// 默认收藏夹
    /// </summary>
    DefaultFavorite,

    /// <summary>
    /// 默认播放器显示模式
    /// </summary>
    DefaultPlayerDisplayMode,

    /// <summary>
    /// 删除
    /// </summary>
    Delete,

    /// <summary>
    /// 删除收藏夹
    /// </summary>
    DeleteFavorite,

    /// <summary>
    /// 是否要删除该收藏夹？
    /// </summary>
    DeleteFavoriteWarning,

    /// <summary>
    /// 简介
    /// </summary>
    Description,

    /// <summary>
    /// 取消全选
    /// </summary>
    DeselectAll,

    /// <summary>
    /// 详情
    /// </summary>
    Detail,

    /// <summary>
    /// 纪录片
    /// </summary>
    Documentary,

    /// <summary>
    /// 国创
    /// </summary>
    DomesticAnime,

    /// <summary>
    /// 双击行为
    /// </summary>
    DoubleClickBehavior,

    /// <summary>
    /// 双击播放器空白区域的行为
    /// </summary>
    DoubleClickBehaviorDescription,

    /// <summary>
    /// 下载
    /// </summary>
    Download,

    /// <summary>
    /// 下载视频
    /// </summary>
    DownloadVideo,

    /// <summary>
    /// 由 BBDown 驱动
    /// </summary>
    DownloadVideoTip,

    /// <summary>
    /// 动态数
    /// </summary>
    DynamicCount,

    /// <summary>
    /// 动态
    /// </summary>
    DynamicFeed,

    /// <summary>
    /// 想查看关注的UP主的动态吗？
    /// </summary>
    DynamicNeedLoginFirst,

    /// <summary>
    /// {0} 的动态评论
    /// </summary>
    DynamicReplyTitle,

    /// <summary>
    /// 编辑
    /// </summary>
    Edit,

    /// <summary>
    /// 表情
    /// </summary>
    Emote,

    /// <summary>
    /// 进入小窗模式
    /// </summary>
    EnterCompactOverlay,

    /// <summary>
    /// 进入全屏模式
    /// </summary>
    EnterFullScreen,

    /// <summary>
    /// 进入全窗口模式
    /// </summary>
    EnterFullWindow,

    /// <summary>
    /// 按下回车以生效
    /// </summary>
    EnterToEffect,

    /// <summary>
    /// 进入用户空间
    /// </summary>
    EnterUserSpace,

    /// <summary>
    /// 分集
    /// </summary>
    Episodes,

    /// <summary>
    /// 退出
    /// </summary>
    Exit,

    /// <summary>
    /// 你也可以选择隐藏应用，并在需要时快速切回来。你可以随时在系统托盘中退出应用
    /// </summary>
    ExitAppDescription,

    /// <summary>
    /// 退出应用？
    /// </summary>
    ExitAppTitle,

    /// <summary>
    /// 退出小窗模式
    /// </summary>
    ExitCompactOverlay,

    /// <summary>
    /// 退出全屏模式
    /// </summary>
    ExitFullScreen,

    /// <summary>
    /// 退出全窗口模式
    /// </summary>
    ExitFullWindow,

    /// <summary>
    /// 退出搜索
    /// </summary>
    ExitSearch,

    /// <summary>
    /// 展开详情
    /// </summary>
    ExpandDetail,

    /// <summary>
    /// 尝试清空历史记录失败，请稍后重试
    /// </summary>
    FailedToClearHisotry,

    /// <summary>
    /// 清除日志失败，请稍后重试
    /// </summary>
    FailedToClearLog,

    /// <summary>
    /// 清除稍后再看列表失败，请稍后重试
    /// </summary>
    FailedToClearViewLater,

    /// <summary>
    /// 获取用户关系信息失败
    /// </summary>
    FailedToGetUserRelation,

    /// <summary>
    /// 二维码加载失败，请刷新
    /// </summary>
    FailedToLoadQRCode,

    /// <summary>
    /// 移除视频收藏失败
    /// </summary>
    FailedToRemoveVideoFromFavorite,

    /// <summary>
    /// 删除观看历史失败
    /// </summary>
    FailedToRemoveVideoFromHistory,

    /// <summary>
    /// 尝试移除视频失败，请稍后重试
    /// </summary>
    FailedToRemoveVideoFromViewLater,

    /// <summary>
    /// 发送弹幕失败，请稍后再试
    /// </summary>
    FailedToSendDanmaku,

    /// <summary>
    /// 粉丝数
    /// </summary>
    FansCount,

    /// <summary>
    /// 的粉丝
    /// </summary>
    FansSuffix,

    /// <summary>
    /// 收藏
    /// </summary>
    Favorite,

    /// <summary>
    /// 收藏失败
    /// </summary>
    FavoriteFailed,

    /// <summary>
    /// 收藏夹内没有视频
    /// </summary>
    FavoriteHaveNoVideos,

    /// <summary>
    /// 选择一个或多个收藏夹收藏视频吧！
    /// </summary>
    FavoriteTip,

    /// <summary>
    /// 精选推荐
    /// </summary>
    FeaturedRecommend,

    /// <summary>
    /// 影视
    /// </summary>
    Film,

    /// <summary>
    /// 60分钟+
    /// </summary>
    FilterByGreaterThan60Min,

    /// <summary>
    /// 0-10分钟
    /// </summary>
    FilterByLessThan10Min,

    /// <summary>
    /// 10-30分钟
    /// </summary>
    FilterByLessThan30Min,

    /// <summary>
    /// 30-60分钟
    /// </summary>
    FilterByLessThan60Min,

    /// <summary>
    /// 全部时长
    /// </summary>
    FilterByTotalDuration,

    /// <summary>
    /// 点击标签后，您将前往搜索页面搜索标签内容，这会中断当前正在播放的视频，是否确认？
    /// </summary>
    FirstClickTagTip,

    /// <summary>
    /// 固定内容
    /// </summary>
    FixContent,

    /// <summary>
    /// 已固定
    /// </summary>
    Fixed,

    /// <summary>
    /// 固定的内容
    /// </summary>
    FixedContent,

    /// <summary>
    /// 固定的剧集
    /// </summary>
    FixedPgcs,

    /// <summary>
    /// 固定的UP
    /// </summary>
    FixedPublishers,

    /// <summary>
    /// 固定剧集
    /// </summary>
    FixPgc,

    /// <summary>
    /// 固定UP
    /// </summary>
    FixPublisher,

    /// <summary>
    /// 目前哔哩不能播放 flv 格式的直播，请在网页中打开该直播间
    /// </summary>
    FlvNotSupported,

    /// <summary>
    /// 关注
    /// </summary>
    Follow,

    /// <summary>
    /// 关注数
    /// </summary>
    FollowCount,

    /// <summary>
    /// 互相关注
    /// </summary>
    FollowEachOther,

    /// <summary>
    /// 已关注
    /// </summary>
    Followed,

    /// <summary>
    /// 关注的直播间
    /// </summary>
    FollowLiveRoom,

    /// <summary>
    /// 关注直播间
    /// </summary>
    FollowRoom,

    /// <summary>
    /// 关注的人
    /// </summary>
    FollowsSuffix,

    /// <summary>
    /// 跟随系统
    /// </summary>
    FollowSystem,

    /// <summary>
    /// 字号
    /// </summary>
    FontSize,

    /// <summary>
    /// 前进
    /// </summary>
    ForwardSkip,

    /// <summary>
    /// 帧率
    /// </summary>
    Fps,

    /// <summary>
    /// 完整
    /// </summary>
    Full,

    /// <summary>
    /// 全屏模式
    /// </summary>
    FullScreenMode,

    /// <summary>
    /// 包括视频标题、简介等信息在内的文本自动转换为繁体中文。用户名等标识信息除外
    /// </summary>
    FullTraditionalChineseDescription,

    /// <summary>
    /// 全盘繁体
    /// </summary>
    FullTraditionalChineseTitle,

    /// <summary>
    /// 全窗口模式
    /// </summary>
    FullWindowMode,

    /// <summary>
    /// 功能说明
    /// </summary>
    FunctionIntroduce,

    /// <summary>
    /// 生成命令
    /// </summary>
    GenerateCommand,

    /// <summary>
    /// 通用
    /// </summary>
    Generic,

    /// <summary>
    /// 正在获取分组
    /// </summary>
    GettingGroups,

    /// <summary>
    /// 正在获取分区...
    /// </summary>
    GettingPartitions,

    /// <summary>
    /// 全局播放速率
    /// </summary>
    GlobalPlaybackRate,

    /// <summary>
    /// 启用后，所有视频共用一个播放速率
    /// </summary>
    GlobalPlaybackRateDescription,

    /// <summary>
    /// 全局代理
    /// </summary>
    GlobeProxy,

    /// <summary>
    /// 不论是否为地区限制的内容，都使用代理服务器解析
    /// </summary>
    GlobeProxyDescription,

    /// <summary>
    /// 已选取 {0} 条热门评论
    /// </summary>
    GotHotComments,

    /// <summary>
    /// 草绿色
    /// </summary>
    Grass,

    /// <summary>
    /// 绿色
    /// </summary>
    Green,

    /// <summary>
    /// 网格布局
    /// </summary>
    GridLayout,

    /// <summary>
    /// AVC/H.264
    /// </summary>
    H264,

    /// <summary>
    /// HEVC/H.265
    /// </summary>
    H265,

    /// <summary>
    /// 硬件解码
    /// </summary>
    HardwareDecode,

    /// <summary>
    /// 您已更新到新版本
    /// </summary>
    HasUpdate,

    /// <summary>
    /// 高清（1080P）优先
    /// </summary>
    HDFirst,

    /// <summary>
    /// 帮助 & 支持
    /// </summary>
    HelpAndSupport,

    /// <summary>
    /// 隐藏
    /// </summary>
    Hide,

    /// <summary>
    /// 隐藏弹幕
    /// </summary>
    HideDanmaku,

    /// <summary>
    /// 关闭时隐藏
    /// </summary>
    HideWhenClose,

    /// <summary>
    /// 关闭窗口时隐藏应用而非退出
    /// </summary>
    HideWhenCloseDescription,

    /// <summary>
    /// 要点
    /// </summary>
    Highlights,

    /// <summary>
    /// 高质量
    /// </summary>
    HighQuality,

    /// <summary>
    /// 首页
    /// </summary>
    Home,

    /// <summary>
    /// 主机路径
    /// </summary>
    Host,

    /// <summary>
    /// 热门
    /// </summary>
    Hot,

    /// <summary>
    /// 热门文章
    /// </summary>
    HotArticle,

    /// <summary>
    /// 最热评论
    /// </summary>
    HotReply,

    /// <summary>
    /// 热搜
    /// </summary>
    HotSearch,

    /// <summary>
    /// 热门标签
    /// </summary>
    HotTags,

    /// <summary>
    /// 小时
    /// </summary>
    Hours,

    /// <summary>
    /// 忽略该版本
    /// </summary>
    IgnoreVersion,

    /// <summary>
    /// 图片展示
    /// </summary>
    ImageGallery,

    /// <summary>
    /// 索引
    /// </summary>
    Index,

    /// <summary>
    /// 洗脑循环
    /// </summary>
    InfinityLoop,

    /// <summary>
    /// 信息
    /// </summary>
    Information,

    /// <summary>
    /// 是否在应用启动时检查上次关闭时正在播放的视频，并提醒继续播放
    /// </summary>
    InitialCheckDescription,

    /// <summary>
    /// 初始化检查
    /// </summary>
    InitialCheckTitle,

    /// <summary>
    /// 输入
    /// </summary>
    Input,

    /// <summary>
    /// 请输入验证码
    /// </summary>
    InputCaptchaTip,

    /// <summary>
    /// 互动视频结束，可点击播放控制器的 "橡皮擦" 按钮返回开头
    /// </summary>
    InteractionEnd,

    /// <summary>
    /// 交互式清晰度选择
    /// </summary>
    InteractionQuality,

    /// <summary>
    /// 接口类型
    /// </summary>
    InterfaceType,

    /// <summary>
    /// 国际应用
    /// </summary>
    InternationalApp,

    /// <summary>
    /// 无效的地址
    /// </summary>
    InvalidAddress,

    /// <summary>
    /// 无效的配置
    /// </summary>
    InvalidConfig,

    /// <summary>
    /// 无效的服务配置
    /// </summary>
    InvalidServiceConfig,

    /// <summary>
    /// 请在设置页面中完善服务配置
    /// </summary>
    InvalidServiceConfigDescription,

    /// <summary>
    /// 用户名或密码错误
    /// </summary>
    InvalidUserNameOrPassword,

    /// <summary>
    /// 不是有效的视频Id
    /// </summary>
    InvalidVideoId,

    /// <summary>
    /// 需要反馈？
    /// </summary>
    IsNeedFeedback,

    /// <summary>
    /// 需要反馈应用使用过程中的问题？
    /// </summary>
    IsNeedFeedbackDescription,

    /// <summary>
    /// 加入 QQ 群
    /// </summary>
    JoinQQGroup,

    /// <summary>
    /// 土黄色
    /// </summary>
    Khaki,

    /// <summary>
    /// 大
    /// </summary>
    Large,

    /// <summary>
    /// 最新
    /// </summary>
    Latest,

    /// <summary>
    /// 最新评论
    /// </summary>
    LatestReply,

    /// <summary>
    /// 左侧
    /// </summary>
    Left,

    /// <summary>
    /// 浅色
    /// </summary>
    Light,

    /// <summary>
    /// 浅蓝色
    /// </summary>
    LightBlue,

    /// <summary>
    /// 浅色
    /// </summary>
    LightTheme,

    /// <summary>
    /// 点赞
    /// </summary>
    Like,

    /// <summary>
    /// 点赞数
    /// </summary>
    LikeCount,

    /// <summary>
    /// 收到的赞
    /// </summary>
    LikeMe,

    /// <summary>
    /// {0}, {1} 等{2}人赞了我的{3}
    /// </summary>
    LikeMessageMultipleDescription,

    /// <summary>
    /// {0} 赞了我的{1}
    /// </summary>
    LikeMessageSingleDescription,

    /// <summary>
    /// 链接
    /// </summary>
    Link,

    /// <summary>
    /// 关联配置
    /// </summary>
    LinkConfig,

    /// <summary>
    /// 列表
    /// </summary>
    List,

    /// <summary>
    /// 列表布局
    /// </summary>
    ListLayout,

    /// <summary>
    /// 直播
    /// </summary>
    Live,

    /// <summary>
    /// 直播信息
    /// </summary>
    LiveInformation,

    /// <summary>
    /// 正在加载直播
    /// </summary>
    LiveInitializing,

    /// <summary>
    /// 直播源地址
    /// </summary>
    LiveSourceUrl,

    /// <summary>
    /// 直播中
    /// </summary>
    Living,

    /// <summary>
    /// 加载中，请稍候
    /// </summary>
    LoadingAndWait,

    /// <summary>
    /// 位置
    /// </summary>
    Location,

    /// <summary>
    /// 已清除日志记录
    /// </summary>
    LogEmptied,

    /// <summary>
    /// 日志文件夹
    /// </summary>
    LoggerFolder,

    /// <summary>
    /// 日志记录
    /// </summary>
    LoggerModule,

    /// <summary>
    /// 查看应用日志或清除日志记录
    /// </summary>
    LoggerModuleDescription,

    /// <summary>
    /// 登录
    /// </summary>
    Login,

    /// <summary>
    /// 登录失败，请稍后重试
    /// </summary>
    LoginFailed,

    /// <summary>
    /// 正片
    /// </summary>
    MainEpisode,

    /// <summary>
    /// 主窗口
    /// </summary>
    MainWindow,

    /// <summary>
    /// 手动
    /// </summary>
    Manual,

    /// <summary>
    /// 标记为想看
    /// </summary>
    MarkWantWatch,

    /// <summary>
    /// 标记为已看
    /// </summary>
    MarkWatched,

    /// <summary>
    /// 标记为在看
    /// </summary>
    MarkWatching,

    /// <summary>
    /// 最大
    /// </summary>
    Maximum,

    /// <summary>
    /// 菜单
    /// </summary>
    Menu,

    /// <summary>
    /// 消息
    /// </summary>
    Message,

    /// <summary>
    /// 最小
    /// </summary>
    Minimum,

    /// <summary>
    /// 分钟
    /// </summary>
    Minutes,

    /// <summary>
    /// 等人
    /// </summary>
    MorePeople,

    /// <summary>
    /// 共{0}条回复 ⪢
    /// </summary>
    MoreReplyDisplay,

    /// <summary>
    /// 电影
    /// </summary>
    Movie,

    /// <summary>
    /// 多窗口
    /// </summary>
    MultipleWindow,

    /// <summary>
    /// 已静音
    /// </summary>
    Muted,

    /// <summary>
    /// 我的
    /// </summary>
    My,

    /// <summary>
    /// 我的动态
    /// </summary>
    MyDynamic,

    /// <summary>
    /// 我的粉丝
    /// </summary>
    MyFans,

    /// <summary>
    /// 我的收藏
    /// </summary>
    MyFavorite,

    /// <summary>
    /// 我的追番
    /// </summary>
    MyFavoriteAnime,

    /// <summary>
    /// 我的追剧
    /// </summary>
    MyFavoriteFilm,

    /// <summary>
    /// 我的关注
    /// </summary>
    MyFollow,

    /// <summary>
    /// 个人主页
    /// </summary>
    MyWebPage,

    /// <summary>
    /// 导航
    /// </summary>
    Navigation,

    /// <summary>
    /// 与视频匹配
    /// </summary>
    NearVideo,

    /// <summary>
    /// 你需要先登录
    /// </summary>
    NeedLoginFirst,

    /// <summary>
    /// 密码登录方式失败，请使用二维码登录
    /// </summary>
    NeedQRLogin,

    /// <summary>
    /// 当前宽度不足以显示消息，请调整应用宽度
    /// </summary>
    NeedScaleToShowMessage,

    /// <summary>
    /// 你需要拉宽应用以显示评论列表
    /// </summary>
    NeedScaleToShowReply,

    /// <summary>
    /// 网络连接错误，请稍后重试
    /// </summary>
    NetworkError,

    /// <summary>
    /// 不再询问我
    /// </summary>
    NeverAskMeAgain,

    /// <summary>
    /// 下一集
    /// </summary>
    NextEpisode,

    /// <summary>
    /// 下一个：{0}
    /// </summary>
    NextPartTipTemplate,

    /// <summary>
    /// 没有找到符合要求的文章
    /// </summary>
    NoArticles,

    /// <summary>
    /// 不转换
    /// </summary>
    NoConvert,

    /// <summary>
    /// 没有可展示的动态
    /// </summary>
    NoDynamics,

    /// <summary>
    /// 可能是网络原因，目前无法展示该用户的动态
    /// </summary>
    NoDynamicsDescription,

    /// <summary>
    /// 您关注的UP主还没有发布更新
    /// </summary>
    NoDynamicUps,

    /// <summary>
    /// 没有可供播放的分集
    /// </summary>
    NoEpisode,

    /// <summary>
    /// 该用户还木有粉丝哟~
    /// </summary>
    NoFans,

    /// <summary>
    /// 没有找到正在追的剧集
    /// </summary>
    NoFavoritesPgc,

    /// <summary>
    /// 收藏夹内还没有视频~
    /// </summary>
    NoFavoriteVideos,

    /// <summary>
    /// 没有获取到精选视频
    /// </summary>
    NoFeaturedVideo,

    /// <summary>
    /// 没有文件
    /// </summary>
    NoFiles,

    /// <summary>
    /// 当前目录下没有可用的文件
    /// </summary>
    NoFilesDescription,

    /// <summary>
    /// 空无一人的关注列表~
    /// </summary>
    NoFollows,

    /// <summary>
    /// 没有最近的文章历史记录
    /// </summary>
    NoHistoryArticles,

    /// <summary>
    /// 没有最近的直播历史记录
    /// </summary>
    NoHistoryLives,

    /// <summary>
    /// 没有最近的视频历史记录
    /// </summary>
    NoHistoryVideos,

    /// <summary>
    /// 没有找到符合要求的直播间
    /// </summary>
    NoLiveRooms,

    /// <summary>
    /// 正在等待发言
    /// </summary>
    NoMessage,

    /// <summary>
    /// 无
    /// </summary>
    None,

    /// <summary>
    /// 没有找到符合要求的剧集
    /// </summary>
    NoPgcSeasons,

    /// <summary>
    /// 目前还没有评论
    /// </summary>
    NoReply,

    /// <summary>
    /// 普通用户
    /// </summary>
    NormalUser,

    /// <summary>
    /// 暂无直播间文本介绍
    /// </summary>
    NoRoomDescription,

    /// <summary>
    /// TA还没有自我介绍哟~
    /// </summary>
    NoSelfIntroduce,

    /// <summary>
    /// 未找到指定的数据
    /// </summary>
    NoSpecificData,

    /// <summary>
    /// 没有指定的下载文件夹
    /// </summary>
    NoSpecifiedDownloadPath,

    /// <summary>
    /// 无描边
    /// </summary>
    NoStroke,

    /// <summary>
    /// 没有可用的字幕，无法总结该视频
    /// </summary>
    NoSubtitle,

    /// <summary>
    /// 通知设置
    /// </summary>
    NotificationSetting,

    /// <summary>
    /// 在应用运行期间提醒你有新的内容
    /// </summary>
    NotificationSettingDescription,

    /// <summary>
    /// 无标题视频
    /// </summary>
    NoTitleVideo,

    /// <summary>
    /// 不受支持的内容
    /// </summary>
    NotSupportContent,

    /// <summary>
    /// 不受支持的动态类型
    /// </summary>
    NotSupportDynamic,

    /// <summary>
    /// 即将更新
    /// </summary>
    NotUpdate,

    /// <summary>
    /// 未更新
    /// </summary>
    NotUpdated,

    /// <summary>
    /// 未验证
    /// </summary>
    NotVerify,

    /// <summary>
    /// 没有找到符合要求的用户
    /// </summary>
    NoUsers,

    /// <summary>
    /// 没有在该用户下找到指定关键词的视频
    /// </summary>
    NoUserVideoSearchResult,

    /// <summary>
    /// 没有可用的播放链接
    /// </summary>
    NoValidPlayUrl,

    /// <summary>
    /// 没有视频被加入稍后再看列表
    /// </summary>
    NoViewLaterVideos,

    /// <summary>
    /// 认证用户
    /// </summary>
    OfficialUser,

    /// <summary>
    /// 一个币
    /// </summary>
    OneCoin,

    /// <summary>
    /// 仅音频
    /// </summary>
    OnlyAudio,

    /// <summary>
    /// 尝试仅播放音频流以节省流量
    /// </summary>
    OnlyAudioDescription,

    /// <summary>
    /// 仅显示序号
    /// </summary>
    OnlyIndex,

    /// <summary>
    /// 仅字幕
    /// </summary>
    OnlySubtitle,

    /// <summary>
    /// 仅视频
    /// </summary>
    OnlyVideo,

    /// <summary>
    /// 打开配置
    /// </summary>
    OpenConfig,

    /// <summary>
    /// 前往下载
    /// </summary>
    OpenDownloadPage,

    /// <summary>
    /// 截图后打开图片
    /// </summary>
    OpenFileAfterScreenshot,

    /// <summary>
    /// 打开文件夹
    /// </summary>
    OpenFolder,

    /// <summary>
    /// 下载完成后打开文件夹
    /// </summary>
    OpenFolderWhenDownloaded,

    /// <summary>
    /// 在浏览器中打开
    /// </summary>
    OpenInBrowser,

    /// <summary>
    /// 点击分区
    /// </summary>
    OpenPartition,

    /// <summary>
    /// 点击分区后可以查看推荐内容及子分区内容
    /// </summary>
    OpenPartitionDescription,

    /// <summary>
    /// 在其它应用中打开
    /// </summary>
    OpenWith,

    /// <summary>
    /// 使用 MPV 播放
    /// </summary>
    OpenWithMpv,

    /// <summary>
    /// 使用 MPV.Net 播放
    /// </summary>
    OpenWithMpvNet,

    /// <summary>
    /// 橘黄色
    /// </summary>
    Orange,

    /// <summary>
    /// 原创
    /// </summary>
    Original,

    /// <summary>
    /// 原名
    /// </summary>
    OriginName,

    /// <summary>
    /// 其它可能的解释
    /// </summary>
    OtherExplain,

    /// <summary>
    /// 输出
    /// </summary>
    Output,

    /// <summary>
    /// 总体评价
    /// </summary>
    OverallEvaluation,

    /// <summary>
    /// 分区
    /// </summary>
    Partition,

    /// <summary>
    /// 正在加载分区
    /// </summary>
    PartitionLoading,

    /// <summary>
    /// 分区排行榜
    /// </summary>
    PartitionRank,

    /// <summary>
    /// 分区请求失败
    /// </summary>
    PartitionRequestFailed,

    /// <summary>
    /// 加入分P前缀
    /// </summary>
    PartPrefix,

    /// <summary>
    /// 分集
    /// </summary>
    Parts,

    /// <summary>
    /// 密码
    /// </summary>
    Password,

    /// <summary>
    /// 请输入密码
    /// </summary>
    PasswordHolder,

    /// <summary>
    /// 请在下方输入您的用户名和密码，应用不会存储这部分数据，但安全起见，请使用二维码登录
    /// </summary>
    PasswordLoginTip,

    /// <summary>
    /// 已暂停
    /// </summary>
    Paused,

    /// <summary>
    /// 人次
    /// </summary>
    PeopleCount,

    /// <summary>
    /// 个人主页
    /// </summary>
    Personal,

    /// <summary>
    /// 正在追
    /// </summary>
    PgcFollowing,

    /// <summary>
    /// 正在加载 PGC 内容
    /// </summary>
    PgcInitializing,

    /// <summary>
    /// 追
    /// </summary>
    PgcNotFollow,

    /// <summary>
    /// 像素格式
    /// </summary>
    PixelFormat,

    /// <summary>
    /// 播放
    /// </summary>
    Play,

    /// <summary>
    /// 播放全部
    /// </summary>
    PlayAll,

    /// <summary>
    /// 播放速率
    /// </summary>
    PlaybackRate,

    /// <summary>
    /// 播放速率增强
    /// </summary>
    PlaybackRateEnhancement,

    /// <summary>
    /// 开启后，播放速率最高支持6倍速，步幅增加为0.1，但较高的速率可能导致视频卡帧，请谨慎调整
    /// </summary>
    PlaybackRateEnhancementDescription,

    /// <summary>
    /// 启用倍速滑动控件
    /// </summary>
    PlaybackRateSliderEnabled,

    /// <summary>
    /// 开启后可以精确控制播放倍速
    /// </summary>
    PlaybackRateSliderEnabledDescription,

    /// <summary>
    /// 播放数
    /// </summary>
    PlayCount,

    /// <summary>
    /// 播放器
    /// </summary>
    Player,

    /// <summary>
    /// 播放器控制
    /// </summary>
    PlayerControl,

    /// <summary>
    /// 包含优先解码以及一些媒体控制器的设置
    /// </summary>
    PlayerControlDescription,

    /// <summary>
    /// 播放控制器操作模式
    /// </summary>
    PlayerControlMode,

    /// <summary>
    /// 自动=控制器自行显示/隐藏，手动=用户控制显示/隐藏
    /// </summary>
    PlayerControlModeDescription,

    /// <summary>
    /// 播放行为
    /// </summary>
    PlayerBehavior,

    /// <summary>
    /// 设置播放器的默认行为
    /// </summary>
    PlayerBehaviorDescription,

    /// <summary>
    /// 播放器类型
    /// </summary>
    PlayerType,

    /// <summary>
    /// 播放器窗口新建行为
    /// </summary>
    PlayerWindowBehavior,

    /// <summary>
    /// 正在播放
    /// </summary>
    Playing,

    /// <summary>
    /// 无痕播放
    /// </summary>
    PlayInPrivate,

    /// <summary>
    /// 线路
    /// </summary>
    PlayLine,

    /// <summary>
    /// 播放列表
    /// </summary>
    Playlist,

    /// <summary>
    /// 播放下一个视频
    /// </summary>
    PlayNextPart,

    /// <summary>
    /// 即将播放下一个视频
    /// </summary>
    PlayNextVideo,

    /// <summary>
    /// 立即播放
    /// </summary>
    PlayNow,

    /// <summary>
    /// 播放/暂停
    /// </summary>
    PlayPause,

    /// <summary>
    /// 请登录
    /// </summary>
    PleaseSignIn,

    /// <summary>
    /// 流行视频
    /// </summary>
    Popular,

    /// <summary>
    /// 流行
    /// </summary>
    PopularSlim,

    /// <summary>
    /// 端口（不需要就填0）
    /// </summary>
    Port,

    /// <summary>
    /// 4K优先
    /// </summary>
    Prefer4K,

    /// <summary>
    /// 在用户已登录并有权限获取4K播放源的情况下，优先播放4K片源
    /// </summary>
    Prefer4KDescription,

    /// <summary>
    /// 音质偏好
    /// </summary>
    PreferAudioQuality,

    /// <summary>
    /// 编码偏好
    /// </summary>
    PreferCodec,

    /// <summary>
    /// 优先选择该编码的视频流，HEVC/H.265 和 AV1 需要额外安装解码器
    /// </summary>
    PreferCodecDescription,

    /// <summary>
    /// 画质优先
    /// </summary>
    PreferHighQuality,

    /// <summary>
    /// 优先播放最高清画质的视频源
    /// </summary>
    PreferHighQualityDescription,

    /// <summary>
    /// 画质偏好
    /// </summary>
    PreferQuality,

    /// <summary>
    /// 预告片
    /// </summary>
    PreviewEpisode,

    /// <summary>
    /// 上一集
    /// </summary>
    PreviousEpisode,

    /// <summary>
    /// 上一个：{0}
    /// </summary>
    PreviousPartTipTemplate,

    /// <summary>
    /// 上次观看：
    /// </summary>
    PreviousView,

    /// <summary>
    /// 项目主页
    /// </summary>
    ProjectHomePage,

    /// <summary>
    /// 协议启动
    /// </summary>
    ProtocolLaunch,

    /// <summary>
    /// 搜索代理
    /// </summary>
    ProxySearchAddress,

    /// <summary>
    /// 发布时间
    /// </summary>
    PublishDate,

    /// <summary>
    /// 开发者的其它应用
    /// </summary>
    PublisherApp,

    /// <summary>
    /// 已完结
    /// </summary>
    PublishFinished,

    /// <summary>
    /// 连载中
    /// </summary>
    PublishInInstalments,

    /// <summary>
    /// 紫色
    /// </summary>
    Purple,

    /// <summary>
    /// 二维码已过期，请刷新
    /// </summary>
    QRCodeExpired,

    /// <summary>
    /// 请使用移动客户端扫描下方的二维码登录
    /// </summary>
    QRLoginTip,

    /// <summary>
    /// 清晰度
    /// </summary>
    Quality,

    /// <summary>
    /// 加入清晰度后缀
    /// </summary>
    QualitySuffix,

    /// <summary>
    /// 快速选择
    /// </summary>
    QuickSelection,

    /// <summary>
    /// 退出应用
    /// </summary>
    QuitApp,

    /// <summary>
    /// 全区排行榜
    /// </summary>
    Rank,

    /// <summary>
    /// 排行榜请求失败
    /// </summary>
    RankRequestFailed,

    /// <summary>
    /// 阅读
    /// </summary>
    Read,

    /// <summary>
    /// 阅读数
    /// </summary>
    ReadCount,

    /// <summary>
    /// 推荐视频
    /// </summary>
    Recommend,

    /// <summary>
    /// 推荐文章
    /// </summary>
    RecommendArticle,

    /// <summary>
    /// 推荐的直播间
    /// </summary>
    RecommendLive,

    /// <summary>
    /// 红色
    /// </summary>
    Red,

    /// <summary>
    /// 刷新
    /// </summary>
    Refresh,

    /// <summary>
    /// 刷新当前分区
    /// </summary>
    RefreshCurrentSection,

    /// <summary>
    /// 关联项目
    /// </summary>
    RelatedProjects,

    /// <summary>
    /// 关联视频
    /// </summary>
    RelatedVideos,

    /// <summary>
    /// 移除
    /// </summary>
    Remove,

    /// <summary>
    /// 移除稍后再看失败
    /// </summary>
    RemoveViewLaterFailed,

    /// <summary>
    /// 是否要删除 {0} 服务？
    /// </summary>
    RemoveWebDavConfigWarning,

    /// <summary>
    /// 重新播放
    /// </summary>
    Replay,

    /// <summary>
    /// 评论
    /// </summary>
    Reply,

    /// <summary>
    /// 评论数
    /// </summary>
    ReplyCount,

    /// <summary>
    /// 评论详情
    /// </summary>
    ReplyDetail,

    /// <summary>
    /// 回复我的
    /// </summary>
    ReplyMe,

    /// <summary>
    /// 对我的{0}发表了{1}条评论
    /// </summary>
    ReplyMessageTypeDescription,

    /// <summary>
    /// 写下你的评论吧~
    /// </summary>
    ReplyPlaceholderText,

    /// <summary>
    /// 回复 @{0}
    /// </summary>
    ReplySomeone,

    /// <summary>
    /// 获取追番列表失败
    /// </summary>
    RequestAnimeFavoriteFailed,

    /// <summary>
    /// 请求文章失败
    /// </summary>
    RequestArticleFailed,

    /// <summary>
    /// 获取收藏文章失败
    /// </summary>
    RequestArticleFavoriteFailed,

    /// <summary>
    /// 文章列表请求失败
    /// </summary>
    RequestArticleListFailed,

    /// <summary>
    /// 获取追剧列表失败
    /// </summary>
    RequestCinemaFavoriteFailed,

    /// <summary>
    /// 请求动态失败
    /// </summary>
    RequestDynamicFailed,

    /// <summary>
    /// 请求表情失败
    /// </summary>
    RequestEmoteFailed,

    /// <summary>
    /// 无法获取表情包，请稍后再试
    /// </summary>
    RequestEmoteFailedDescription,

    /// <summary>
    /// 获取粉丝数据时失败
    /// </summary>
    RequestFansFailed,

    /// <summary>
    /// 请求收藏夹失败
    /// </summary>
    RequestFavoriteError,

    /// <summary>
    /// 数据源详情请求失败
    /// </summary>
    RequestFeedDetailFailed,

    /// <summary>
    /// 请求关注列表失败
    /// </summary>
    RequestFollowsFailed,

    /// <summary>
    /// 请求历史记录失败
    /// </summary>
    RequestHistoryFailed,

    /// <summary>
    /// 获取索引过滤条件失败
    /// </summary>
    RequestIndexFilterFailed,

    /// <summary>
    /// 请求索引结果失败
    /// </summary>
    RequestIndexResultFailed,

    /// <summary>
    /// 直播数据请求失败
    /// </summary>
    RequestLiveFailed,

    /// <summary>
    /// 请求直播播放信息失败
    /// </summary>
    RequestLivePlayInformationFailed,

    /// <summary>
    /// 请求直播标签失败
    /// </summary>
    RequestLiveTagsFailed,

    /// <summary>
    /// 请求消息失败
    /// </summary>
    RequestMessageFailed,

    /// <summary>
    /// PGC内容请求失败
    /// </summary>
    RequestPgcFailed,

    /// <summary>
    /// 请求时间线内容失败
    /// </summary>
    RequestPgcTimeLineFailed,

    /// <summary>
    /// 请求播放列表失败
    /// </summary>
    RequestPlayListFailed,

    /// <summary>
    /// 请求热门视频失败
    /// </summary>
    RequestPopularFailed,

    /// <summary>
    /// 请求推荐视频失败
    /// </summary>
    RequestRecommendFailed,

    /// <summary>
    /// 请求评论失败
    /// </summary>
    RequestReplyFailed,

    /// <summary>
    /// 没有查找到相关的搜索结果
    /// </summary>
    RequestSearchResultFailed,

    /// <summary>
    /// 请求分区视频失败
    /// </summary>
    RequestSubPartitionFailed,

    /// <summary>
    /// 标签页详情数据请求失败
    /// </summary>
    RequestTabDetailFailed,

    /// <summary>
    /// 请求用户信息失败
    /// </summary>
    RequestUserInformationFailed,

    /// <summary>
    /// 视频播放信息请求失败
    /// </summary>
    RequestVideoFailed,

    /// <summary>
    /// 请求视频收藏夹信息失败
    /// </summary>
    RequestVideoFavoriteFailed,

    /// <summary>
    /// 请求稍后再看列表失败
    /// </summary>
    RequestViewLaterFailed,

    /// <summary>
    /// 重置配置
    /// </summary>
    ResetConfig,

    /// <summary>
    /// 根目录
    /// </summary>
    RootDirectory,

    /// <summary>
    /// 旋转
    /// </summary>
    Rotate,

    /// <summary>
    /// 保存
    /// </summary>
    Save,

    /// <summary>
    /// 已保存
    /// </summary>
    Saved,

    /// <summary>
    /// 另存为
    /// </summary>
    SaveTo,

    /// <summary>
    /// 保存到图库
    /// </summary>
    SaveToPictureLibrary,

    /// <summary>
    /// 评分
    /// </summary>
    Score,

    /// <summary>
    /// 截图
    /// </summary>
    Screenshot,

    /// <summary>
    /// 截图文件夹
    /// </summary>
    ScreenshotFolder,

    /// <summary>
    /// 截图设置
    /// </summary>
    ScreenshotSettings,

    /// <summary>
    /// 包含对截图后行为的一些设置
    /// </summary>
    ScreenshotSettingsDescription,

    /// <summary>
    /// 已成功截图
    /// </summary>
    ScreenshotSuccess,

    /// <summary>
    /// 滚动弹幕
    /// </summary>
    ScrollDanmaku,

    /// <summary>
    /// 搜索
    /// </summary>
    Search,

    /// <summary>
    /// 在网页中搜索
    /// </summary>
    SearchInWeb,

    /// <summary>
    /// 搜索视频、番剧或UP主
    /// </summary>
    SearchTip,

    /// <summary>
    /// 搜一搜
    /// </summary>
    SearchTipSlim,

    /// <summary>
    /// 合集中还没有视频
    /// </summary>
    SeasonHasNoVideos,

    /// <summary>
    /// 系列
    /// </summary>
    Seasons,

    /// <summary>
    /// 秒
    /// </summary>
    Seconds,

    /// <summary>
    /// 相关内容
    /// </summary>
    Sections,

    /// <summary>
    /// 查看全部
    /// </summary>
    SeeAll,

    /// <summary>
    /// 查看详情
    /// </summary>
    SeeDetail,

    /// <summary>
    /// 全选
    /// </summary>
    SelectAll,

    /// <summary>
    /// 选择排序方式
    /// </summary>
    SelectSortType,

    /// <summary>
    /// 发送反馈
    /// </summary>
    SendFeedback,

    /// <summary>
    /// 正在发送消息...
    /// </summary>
    SendingMessage,

    /// <summary>
    /// 发送消息
    /// </summary>
    SendMessage,

    /// <summary>
    /// 服务
    /// </summary>
    Service,

    /// <summary>
    /// 成功设置地址
    /// </summary>
    SetAddressSuccess,

    /// <summary>
    /// 设置失败
    /// </summary>
    SetFailed,

    /// <summary>
    /// 已成功设置
    /// </summary>
    SetSuccess,

    /// <summary>
    /// 设置
    /// </summary>
    Settings,

    /// <summary>
    /// 设置为
    /// </summary>
    SettingTo,

    /// <summary>
    /// 设置为背景
    /// </summary>
    SettingToBackground,

    /// <summary>
    /// 设置为锁屏
    /// </summary>
    SettingToLockScreen,

    /// <summary>
    /// 阴影
    /// </summary>
    Shadow,

    /// <summary>
    /// 分享
    /// </summary>
    Share,

    /// <summary>
    /// 分享链接
    /// </summary>
    ShareLink,

    /// <summary>
    /// 显示
    /// </summary>
    Show,

    /// <summary>
    /// 显示弹幕
    /// </summary>
    ShowDanmaku,

    /// <summary>
    /// 显示更多
    /// </summary>
    ShowMore,

    /// <summary>
    /// 显示字幕
    /// </summary>
    ShowSubtitle,

    /// <summary>
    /// 已登录
    /// </summary>
    SignedIn,

    /// <summary>
    /// 登录
    /// </summary>
    SignIn,

    /// <summary>
    /// 用户登录
    /// </summary>
    SignInTitle,

    /// <summary>
    /// 退出账户
    /// </summary>
    SignOut,

    /// <summary>
    /// 单次快进/快退时长
    /// </summary>
    SingleFastForwardAndRewindSpan,

    /// <summary>
    /// 单次按下键盘左右方向键时的快进/快退跳跃时长（秒）
    /// </summary>
    SingleFastForwardAndRewindSpanDescription,

    /// <summary>
    /// 单窗口
    /// </summary>
    SingleWindow,

    /// <summary>
    /// 小号
    /// </summary>
    Small,

    /// <summary>
    /// 软件解码
    /// </summary>
    SoftwareDecode,

    /// <summary>
    /// {0}的直播间
    /// </summary>
    SomeoneLiveRoom,

    /// <summary>
    /// 弹幕最多
    /// </summary>
    SortByDanmaku,

    /// <summary>
    /// 默认排序
    /// </summary>
    SortByDefault,

    /// <summary>
    /// 粉丝数由高到低
    /// </summary>
    SortByFansHTL,

    /// <summary>
    /// 粉丝数由低到高
    /// </summary>
    SortByFansLTH,

    /// <summary>
    /// 收藏最多
    /// </summary>
    SortByFavorite,

    /// <summary>
    /// 最热
    /// </summary>
    SortByHot,

    /// <summary>
    /// 等级由高到低
    /// </summary>
    SortByLevelHTL,

    /// <summary>
    /// 等级由低到高
    /// </summary>
    SortByLevelLTH,

    /// <summary>
    /// 点赞最多
    /// </summary>
    SortByLike,

    /// <summary>
    /// 最新发布
    /// </summary>
    SortByNewest,

    /// <summary>
    /// 播放最多
    /// </summary>
    SortByPlay,

    /// <summary>
    /// 阅读最多
    /// </summary>
    SortByRead,

    /// <summary>
    /// 评论最多
    /// </summary>
    SortByReply,

    /// <summary>
    /// 不支持该源
    /// </summary>
    SourceNotSupported,

    /// <summary>
    /// 专栏
    /// </summary>
    SpecialColumn,

    /// <summary>
    /// 标准
    /// </summary>
    Standard,

    /// <summary>
    /// 开始下载
    /// </summary>
    StartDownload,

    /// <summary>
    /// 启动方式
    /// </summary>
    StartMethod,

    /// <summary>
    /// 您可以选择应用的启动方式以更快速地打开应用
    /// </summary>
    StartMethodDescription,

    /// <summary>
    /// 开始倍速播放
    /// </summary>
    StartQuickPlay,

    /// <summary>
    /// 开始录制
    /// </summary>
    StartRecording,

    /// <summary>
    /// 自启动
    /// </summary>
    Startup,

    /// <summary>
    /// 将应用添加到开机启动项，应用将在系统启动后自动打开，并以最小化形式显示在任务栏
    /// </summary>
    StartupDescription,

    /// <summary>
    /// 启动项由您的组织或组策略管理，应用启动项已被禁用
    /// </summary>
    StartupDisabledByPolicy,

    /// <summary>
    /// 启动项由用户手动禁用，您需要手动启用才能生效
    /// </summary>
    StartupDisabledByUser,

    /// <summary>
    /// 停止录制
    /// </summary>
    StopRecording,

    /// <summary>
    /// 求个好评
    /// </summary>
    StoreComment,

    /// <summary>
    /// 描边
    /// </summary>
    Stroke,

    /// <summary>
    /// 字幕
    /// </summary>
    Subtitle,

    /// <summary>
    /// 字幕转换
    /// </summary>
    SubtitleConvert,

    /// <summary>
    /// 字幕列表
    /// </summary>
    SubtitleList,

    /// <summary>
    /// 已选择字幕："{0}"
    /// </summary>
    SubtitleSelected,

    /// <summary>
    /// 总结内容
    /// </summary>
    SummarizeContent,

    /// <summary>
    /// 请总结 《{0}》的内容
    /// </summary>
    SummarizeMessage,

    /// <summary>
    /// 总结
    /// </summary>
    Summary,

    /// <summary>
    /// 用密码登录
    /// </summary>
    SwitchToPasswordLogin,

    /// <summary>
    /// 扫描二维码登录
    /// </summary>
    SwitchToQRLogin,

    /// <summary>
    /// 使用系统设置
    /// </summary>
    SystemDefault,

    /// <summary>
    /// 繁体 -> 简体
    /// </summary>
    TC2SC,

    /// <summary>
    /// 万
    /// </summary>
    TenThousands,

    /// <summary>
    /// 时间表
    /// </summary>
    TimeChart,

    /// <summary>
    /// 这一天没有新的内容
    /// </summary>
    TimelineHasNoVideo,

    /// <summary>
    /// 提醒
    /// </summary>
    Tip,

    /// <summary>
    /// 切换弹幕控制器显隐
    /// </summary>
    ToggleDanmakuBarVisibility,

    /// <summary>
    /// 工具箱
    /// </summary>
    Toolbox,

    /// <summary>
    /// 置顶
    /// </summary>
    Top,

    /// <summary>
    /// 顶部
    /// </summary>
    TopDanmaku,

    /// <summary>
    /// 专题
    /// </summary>
    Topic,

    /// <summary>
    /// 全部
    /// </summary>
    Total,

    /// <summary>
    /// 全部标签
    /// </summary>
    TotalTags,

    /// <summary>
    /// 全部用户
    /// </summary>
    TotalUser,

    /// <summary>
    /// 追番/追剧数
    /// </summary>
    TrackCount,

    /// <summary>
    /// 三连
    /// </summary>
    Triple,

    /// <summary>
    /// 要不顺便来个一键三连？赞赏他人，取悦自己 😉
    /// </summary>
    TripleTip,

    /// <summary>
    /// 电视剧
    /// </summary>
    TV,

    /// <summary>
    /// 电视
    /// </summary>
    TVApp,

    /// <summary>
    /// 两个币
    /// </summary>
    TwoCoin,

    /// <summary>
    /// 视频合集
    /// </summary>
    UgcSeason,

    /// <summary>
    /// 超高清（4K）优先
    /// </summary>
    UHDFirst,

    /// <summary>
    /// 取消收藏
    /// </summary>
    UnFavorite,

    /// <summary>
    /// 是否不再关注该收藏夹？
    /// </summary>
    UnFavoriteWarning,

    /// <summary>
    /// 取消固定
    /// </summary>
    UnfixContent,

    /// <summary>
    /// 取消固定UP
    /// </summary>
    UnfixPublisher,

    /// <summary>
    /// 未知错误发生了
    /// </summary>
    UnknownError,

    /// <summary>
    /// 已更新
    /// </summary>
    Updated,

    /// <summary>
    /// UP主
    /// </summary>
    UpMaster,

    /// <summary>
    /// 使用云屏蔽配置
    /// </summary>
    UseCloudShieldSettings,

    /// <summary>
    /// 用户
    /// </summary>
    User,

    /// <summary>
    /// 用户没有投稿视频
    /// </summary>
    UserHaveNoVideos,

    /// <summary>
    /// 用户信息
    /// </summary>
    UserInformation,

    /// <summary>
    /// 用户名
    /// </summary>
    UserName,

    /// <summary>
    /// 请输入用户名/手机
    /// </summary>
    UserNameHolder,

    /// <summary>
    /// 的空间
    /// </summary>
    UserSpaceTitle,

    /// <summary>
    /// 使用网页播放器
    /// </summary>
    UseWebPlayer,

    /// <summary>
    /// 开启后，应用将会在播放单个视频时使用网页代替本地播放器（需要先进行登录验证）
    /// </summary>
    UseWebPlayerDescription,

    /// <summary>
    /// 请输入有效的用户名或密码
    /// </summary>
    ValidUserNameOrPasswordTip,

    /// <summary>
    /// 验证中...
    /// </summary>
    Verifying,

    /// <summary>
    /// 版本
    /// </summary>
    Version,

    /// <summary>
    /// 视频
    /// </summary>
    Video,

    /// <summary>
    /// 视频编解码器
    /// </summary>
    VideoCodec,

    /// <summary>
    /// 视频数
    /// </summary>
    VideoCount,

    /// <summary>
    /// 新视频动态通知
    /// </summary>
    VideoDynamicNotification,

    /// <summary>
    /// 正在加载视频
    /// </summary>
    VideoInitializing,

    /// <summary>
    /// 视频分区
    /// </summary>
    VideoPartition,

    /// <summary>
    /// 已选择分P：“{0}”
    /// </summary>
    VideoPartSelected,

    /// <summary>
    /// 视频
    /// </summary>
    Videos,

    /// <summary>
    /// 视频尺寸
    /// </summary>
    VideoSize,

    /// <summary>
    /// 视频源地址
    /// </summary>
    VideoSourceUrl,

    /// <summary>
    /// 视频播放地址
    /// </summary>
    VideoUrl,

    /// <summary>
    /// 观看
    /// </summary>
    View,

    /// <summary>
    /// 观看人数
    /// </summary>
    Viewer,

    /// <summary>
    /// 观看历史
    /// </summary>
    ViewHistory,

    /// <summary>
    /// 稍后再看
    /// </summary>
    ViewLater,

    /// <summary>
    /// 大会员
    /// </summary>
    Vip,

    /// <summary>
    /// 想看
    /// </summary>
    WantWatch,

    /// <summary>
    /// 已看
    /// </summary>
    Watched,

    /// <summary>
    /// 在看
    /// </summary>
    Watching,

    /// <summary>
    /// 观看列表
    /// </summary>
    Watchlist,

    /// <summary>
    /// 网页
    /// </summary>
    Web,

    /// <summary>
    /// 网页登录
    /// </summary>
    WebSignIn,

    /// <summary>
    /// 欢迎使用哔哩助理
    /// </summary>
    WelcomeUse,

    /// <summary>
    /// 白色
    /// </summary>
    White,

    /// <summary>
    /// 全区
    /// </summary>
    WholePartitions,

    /// <summary>
    /// 词语解释
    /// </summary>
    WordExplain,

    /// <summary>
    /// 黄色
    /// </summary>
    Yellow,

    /// <summary>
    /// 放大
    /// </summary>
    ZoomIn,

    /// <summary>
    /// 缩小
    /// </summary>
    ZoomOut,

    /// <summary>
    /// 播放下一P：{0}
    /// </summary>
    PlayNextPartTipTemplate,

    /// <summary>
    /// 播放下一个视频：{0}
    /// </summary>
    PlayNextVideoTipTemplate,

    /// <summary>
    /// 无痕播放模式，该模式下不会上报播放进度
    /// </summary>
    PlayInPrivateTip,

    /// <summary>
    /// 准备播放下一个视频：{0}
    /// </summary>
    NextVideoNotificationTemplate,

    /// <summary>
    /// 对于互动视频的支持，开发者表示心累，暂时不处理，请先使用网页把玩吧~
    /// </summary>
    InteractionNotSupportTip,

    /// <summary>
    /// 重载
    /// </summary>
    Reload,

    /// <summary>
    /// 准备播放下一集：{0}
    /// </summary>
    NextEpisodeNotificationTemplate,

    /// <summary>
    /// 播放下一集：{0}
    /// </summary>
    PlayNextEpisodeTipTemplate,

    /// <summary>
    /// 复制分集地址
    /// </summary>
    CopyEpisodeUrl,

    /// <summary>
    /// 复制剧集地址
    /// </summary>
    CopySeasonUrl,

    /// <summary>
    /// 复制直播间地址
    /// </summary>
    CopyLiveUrl,

    /// <summary>
    /// {0}开始直播
    /// </summary>
    LiveStartTimeTemplate,

    /// <summary>
    /// 不使用 P2P 节点
    /// </summary>
    NoP2P,

    /// <summary>
    /// 将会尝试使用从非 MCDN/PCDN 节点获取视频和音频流
    /// </summary>
    NoP2PDescription,

    /// <summary>
    /// 解码偏好
    /// </summary>
    PreferDecode,

    /// <summary>
    /// 优先选择指定的解码器（请选择适用自身硬件的解码器）
    /// </summary>
    PreferDecodeDescription,

    /// <summary>
    /// D3D11 硬解
    /// </summary>
    D3D11Decode,

    /// <summary>
    /// NVDEC 硬解（仅限N卡）
    /// </summary>
    NVDECDecode,

    /// <summary>
    /// DXVA2 硬解
    /// </summary>
    DXVA2Decode,

    /// <summary>
    /// 原生
    /// </summary>
    Native,

    /// <summary>
    /// 追番/追剧失败
    /// </summary>
    FailedToFollowPgc,

    /// <summary>
    /// 已取消关注
    /// </summary>
    Unfollowed,

    /// <summary>
    /// 取消追番/追剧失败
    /// </summary>
    FailedToUnfollowPgc,

    /// <summary>
    /// 状态标记失败
    /// </summary>
    FailedToMarkPgc,

    /// <summary>
    /// 取消关注
    /// </summary>
    Unfollow,

    /// <summary>
    /// 取消关注该用户时失败，请稍后再试
    /// </summary>
    FailedToUnfollowUser,

    /// <summary>
    /// 关注用户时失败，请稍后再试
    /// </summary>
    FailedToFollowUser,

    /// <summary>
    /// 移除文章收藏时失败
    /// </summary>
    FailedToUnfavoriteArticle,

    /// <summary>
    /// 加载聊天消息失败
    /// </summary>
    FailedToLoadChatMessages,

    /// <summary>
    /// 加载聊天会话列表失败
    /// </summary>
    FailedToLoadChatSessions,

    /// <summary>
    /// 发送消息失败，请稍后再试
    /// </summary>
    FailedToSendMessage,

    /// <summary>
    /// TA撤回了一条消息
    /// </summary>
    MessageWithdrawn,

    /// <summary>
    /// 批量下载
    /// </summary>
    BatchDownload,

    /// <summary>
    /// 下载封面
    /// </summary>
    DownloadCover,

    /// <summary>
    /// 下载弹幕
    /// </summary>
    DownloadDanmaku,

    /// <summary>
    /// 杂项
    /// </summary>
    Extra,

    /// <summary>
    /// 下载设置
    /// </summary>
    DownloadSetting,

    /// <summary>
    /// 控制视频下载的默认行为
    /// </summary>
    DownloadSettingDescription,

    /// <summary>
    /// 默认下载文件夹
    /// </summary>
    DefaultDownloadFolder,

    /// <summary>
    /// 文件夹不存在，请重新指定文件夹
    /// </summary>
    FolderNotExist,

    /// <summary>
    /// 下载视频同时下载弹幕
    /// </summary>
    DownloadWithDanmaku,

    /// <summary>
    /// 下载所有分P
    /// </summary>
    DownloadAllParts,

    /// <summary>
    /// 指定分P下载
    /// </summary>
    SelectPartsDownload,

    /// <summary>
    /// 选择指定分集或范围，示例：
    /// - 下载第2集，输入 2
    /// - 下载第1集和第4集，输入 1,4 （半角逗号分隔）
    /// - 下载第1集到第4集，输入 1-4
    /// - 下载全部分集，输入 ALL
    /// - 下载最后一集，输入 LAST
    /// </summary>
    DownloadSelectPartTip,

    /// <summary>
    /// 下载时仅复制命令
    /// </summary>
    CopyCommandWhenDownload,

    /// <summary>
    /// 尝试下载对应内容时仅复制生成的命令而不实际下载
    /// </summary>
    CopyCommandWhenDownloadDescription,

    /// <summary>
    /// 生成命令时不包含身份验证
    /// </summary>
    GenCommandWithoutCredential,

    /// <summary>
    /// 在生成命令时去除 Cookie, 访问令牌等身份信息
    /// </summary>
    GenCommandWithoutCredentialDescription,

    /// <summary>
    /// 下载时调用外部BBDown
    /// </summary>
    UseExternalBBDown,

    /// <summary>
    /// 尝试调用你自己配置的 BBDown 进行下载
    /// </summary>
    UseExternalBBDownDescription,

    /// <summary>
    /// 播放失败
    /// </summary>
    FailedToPlay,

    /// <summary>
    /// 由于某种原因，播放失败了，请点击下方的重载按钮再试试吧
    /// </summary>
    FailedToPlayDescription,

    /// <summary>
    /// 在新窗口中打开
    /// </summary>
    OpenInNewWindow,

    /// <summary>
    /// 创建 WebDAV 配置
    /// </summary>
    CreateWebDavConfig,

    /// <summary>
    /// 编辑 WebDAV 配置
    /// </summary>
    EditWebDavConfig,

    /// <summary>
    /// 当前选择的 WebDAV 服务
    /// </summary>
    CurrentWebDavServiceDescription,

    /// <summary>
    /// 当前没有可用的 WebDAV 服务
    /// </summary>
    NoWebDavService,

    /// <summary>
    /// WebDAV 设置 [预览]
    /// </summary>
    WebDavSettings,

    /// <summary>
    /// 使用本地播放器播放 WebDAV 内的视频内容 [预览功能，可能会在未来移除]
    /// </summary>
    WebDavSettingsDescription,

    /// <summary>
    /// 添加服务
    /// </summary>
    AddService,

    /// <summary>
    /// WebDAV
    /// </summary>
    WebDav,

    /// <summary>
    /// 路径
    /// </summary>
    Path,

    /// <summary>
    /// 推荐的直播分区
    /// </summary>
    RecommendLivePartition,

    /// <summary>
    /// 外部播放器
    /// </summary>
    ExternalPlayer,

    /// <summary>
    /// 外部播放器类型
    /// </summary>
    ExternalPlayerType,

    /// <summary>
    /// 选择用哪一个外部播放器播放视频
    /// </summary>
    ExternalPlayerTypeDescription,

    /// <summary>
    /// 请在外部播放器中观看内容
    /// </summary>
    WatchOnExternalPlayer,

    /// <summary>
    /// 模型已经存在，请勿重复创建
    /// </summary>
    ModelAlreadyExist,

    /// <summary>
    /// 创建自定义模型
    /// </summary>
    CreateCustomModel,

    /// <summary>
    /// 使用的模型不在列表中？那就创建一个吧！
    /// </summary>
    AddYourCustomModel,

    /// <summary>
    /// 自定义模型
    /// </summary>
    CustomModel,

    /// <summary>
    /// 修改自定义模型
    /// </summary>
    ModifyCustomModel,

    /// <summary>
    /// 对话模型设置
    /// </summary>
    ChatModelsSettings,

    /// <summary>
    /// 模型 ID
    /// </summary>
    ModelId,

    /// <summary>
    /// 模型 ID 是该模型的真实标识名称，AI 服务通过此标识确定模型
    /// </summary>
    ModelIdDescription,

    /// <summary>
    /// 模型列表
    /// </summary>
    ModelList,

    /// <summary>
    /// 模型名称
    /// </summary>
    ModelName,

    /// <summary>
    /// 模型名称是应用内部显示在界面上的可读名称
    /// </summary>
    ModelNameDescription,

    /// <summary>
    /// 模型 ID 或名称不能为空
    /// </summary>
    ModelNameOrIdCanNotBeEmpty,

    /// <summary>
    /// 预定义模型
    /// </summary>
    PredefinedModels,

    /// <summary>
    /// 查看 {0} 的内置模型列表
    /// </summary>
    PredefinedModelsDescription,

    /// <summary>
    /// 查看全部模型
    /// </summary>
    SeeAllModels,

    /// <summary>
    /// 如 "ChatGPT 3.5"
    /// </summary>
    ModelNamePlaceholder,

    /// <summary>
    /// 如 "gpt-3.5-turbo"
    /// </summary>
    ModelIdPlaceholder,

    /// <summary>
    /// 查看说明
    /// </summary>
    ShowInformation,

    /// <summary>
    /// 名称
    /// </summary>
    Name,

    /// <summary>
    /// 更多选项
    /// </summary>
    MoreOptions,

    /// <summary>
    /// 修改
    /// </summary>
    Modify,

    /// <summary>
    /// API 版本
    /// </summary>
    ApiVersion,

    /// <summary>
    /// 选择合适的 Azure Open AI 的 API 版本
    /// </summary>
    AzureApiVersionDescription,

    /// <summary>
    /// 在 Azure 门户相应资源的 "密钥与终结点" 中找到此值，可用 KEY1 或 KEY2
    /// </summary>
    AzureOpenAIAccessKeyDescription,

    /// <summary>
    /// 在 Azure 门户相应资源的 "密钥与终结点" 中找到此值
    /// </summary>
    AzureOpenAIEndpointDescription,

    /// <summary>
    /// 在 Azure 门户相应资源的 "密钥与终结点" 中找到此值
    /// </summary>
    AzureRegionDescription,

    /// <summary>
    /// 终结点（API）
    /// </summary>
    Endpoint,

    /// <summary>
    /// 必须包含 http(s)://
    /// </summary>
    EndpointDescription,

    /// <summary>
    /// 如 https://api.openai.com/v1
    /// </summary>
    EndpointPlaceholder,

    /// <summary>
    /// 访问密钥
    /// </summary>
    AccessKey,

    /// <summary>
    /// 填入来自 {0} 的 API 密钥
    /// </summary>
    AccessKeyDescription,

    /// <summary>
    /// {0} API 密钥
    /// </summary>
    AccessKeyPlaceholder,

    /// <summary>
    /// 访问密文（AccessKey Secret）
    /// </summary>
    AccessKeySecret,

    /// <summary>
    /// 在阿里云中注册并获取密钥
    /// </summary>
    AliAccessKeyDescription,

    /// <summary>
    /// 在腾讯云中注册并获取访问密钥
    /// </summary>
    TencentAccessKeyDescription,

    /// <summary>
    /// 在火山引擎的 "API访问密钥" 中获取 Secret Access Key
    /// </summary>
    VolcanoAccessKeyDescription,

    /// <summary>
    /// 在火山引擎的 "API访问密钥" 中获取 Access Key ID
    /// </summary>
    VolcanoKeyIdDescription,

    /// <summary>
    /// 创建
    /// </summary>
    Create,

    /// <summary>
    /// 应用
    /// </summary>
    App,

    /// <summary>
    /// API 密钥（API Key）
    /// </summary>
    ApiKey,

    /// <summary>
    /// 密文 ID（Secret ID）
    /// </summary>
    SecretId,

    /// <summary>
    /// 密文密钥（Secret Key）
    /// </summary>
    SecretKey,

    /// <summary>
    /// 从腾讯云控制台的 "API密钥管理" 中获取密钥
    /// </summary>
    HunYuanSecretDescription,

    /// <summary>
    /// 如果没有则不填
    /// </summary>
    OptionalPlaceholder,

    /// <summary>
    /// 组织（可选）
    /// </summary>
    Organization_Optional,

    /// <summary>
    /// 从百度千帆大模型平台的 "应用接入" 中获取 Secret Key
    /// </summary>
    QianFanSecretDescription,

    /// <summary>
    /// 在讯飞开放平台中注册应用并获取 APPID
    /// </summary>
    SparkDeskAppIdDescription,

    /// <summary>
    /// 应用 ID
    /// </summary>
    AppId,

    /// <summary>
    /// 密文（Secret）
    /// </summary>
    Secret,

    /// <summary>
    /// 在讯飞开放平台中注册应用并获取 Secret
    /// </summary>
    SparkDeskSecretDescription,

    /// <summary>
    /// 没有可用的 AI 服务
    /// </summary>
    NoAIService,

    /// <summary>
    /// 请在设置页面配置所需的 AI 服务
    /// </summary>
    NoAIServiceDescription,

    /// <summary>
    /// 没有可用的模型
    /// </summary>
    NoAIModel,

    /// <summary>
    /// 请在设置页面添加 AI 模型
    /// </summary>
    NoAIModelDescription,

    /// <summary>
    /// 用户已取消
    /// </summary>
    UserCancelled,

    /// <summary>
    /// 没有找到可用的字幕数据
    /// </summary>
    NoSubtitleAvailable,

    /// <summary>
    /// 正在获取字幕元数据...
    /// </summary>
    GettingSubtitleMeta,

    /// <summary>
    /// 正在获取字幕文本内容...
    /// </summary>
    GettingSubtitleInformation,

    /// <summary>
    /// 正在总结...
    /// </summary>
    Summarizing,

    /// <summary>
    /// AI服务
    /// </summary>
    AIService,

    /// <summary>
    /// 复制
    /// </summary>
    Copy,

    /// <summary>
    /// 询问更多
    /// </summary>
    MorePrompts,

    /// <summary>
    /// 擦掉答案
    /// </summary>
    DiscardAnswer,

    /// <summary>
    /// 重新生成
    /// </summary>
    Regenerate,

    /// <summary>
    /// 复制答案
    /// </summary>
    CopyAnswer,

    /// <summary>
    /// 正在获取热门评论
    /// </summary>
    GettingHotComments,

    /// <summary>
    /// 没有获取到有效的文章内容
    /// </summary>
    ArticleContentEmpty,

    /// <summary>
    /// 生成中...
    /// </summary>
    Generating,

    /// <summary>
    /// 询问有关上下文的问题
    /// </summary>
    AskQuestionAboutContext,

    /// <summary>
    /// 该条目已经固定过，请在固定列表中查看
    /// </summary>
    AlreadyPinned,

    /// <summary>
    /// 播放当前列表
    /// </summary>
    PlayCurrentList,

    /// <summary>
    /// 获取用户信息时失败
    /// </summary>
    FailedToGetUserInformation,

    /// <summary>
    /// 用户空间
    /// </summary>
    UserSpace,

    /// <summary>
    /// 尝试获取用户视频时失败
    /// </summary>
    FailedToSearchUserVideos,

    /// <summary>
    /// 点击下方按钮来查看更新内容吧！
    /// </summary>
    HasUpdateDescription,

    /// <summary>
    /// 查看更新
    /// </summary>
    OpenUpdate,

    /// <summary>
    /// 下载字幕
    /// </summary>
    DownloadSubtitle,

    /// <summary>
    /// 新窗口
    /// </summary>
    NewWindow,

    /// <summary>
    /// 跳过 AI 字幕下载
    /// </summary>
    SkipAISubtitle,

    /// <summary>
    /// 切换下一个视频时不显示提示
    /// </summary>
    PlayNextWithoutTip,

    /// <summary>
    /// 自动播放下一个视频时不显示5秒的切换提示
    /// </summary>
    PlayNextWithoutTipDescription,

    /// <summary>
    /// 在播放列表结尾终止
    /// </summary>
    StopWhenEndOfPlaylist,

    /// <summary>
    /// 当播放到播放列表最后一个视频时，不再切换到其它视频
    /// </summary>
    StopWhenEndOfPlaylistDescription,

    /// <summary>
    /// 单个循环
    /// </summary>
    SingleLoop,

    /// <summary>
    /// 列表循环
    /// </summary>
    ListLoop,

    /// <summary>
    /// 不循环
    /// </summary>
    NoLoop,

    /// <summary>
    /// AI 如何配置？
    /// </summary>
    AISettingHeaderTitle,

    /// <summary>
    /// 哔哩助理和小幻助理采用同样的 AI 配置，请点击右侧按钮查看说明文档
    /// </summary>
    AISettingHeaderDescription,

    /// <summary>
    /// 如果其它类型闪退严重，请使用网页播放器
    /// </summary>
    PlayerTypeDescription,

    /// <summary>
    /// 应用检测到您当前的设备中存在 AMD GPU。目前内置的 MPV 播放器在 AMD 平台无法正常工作，请尝试切换到原生播放器，或者使用其它的播放器类型
    /// </summary>
    AmdGpuWarning,

    /// <summary>
    /// 阅读文档
    /// </summary>
    ReadDocument,

    /// <summary>
    /// 顶部导航栏可见性
    /// </summary>
    TopNavVisibility,

    /// <summary>
    /// 是否显示顶部导航栏（包括收藏/稍后再看/历史记录）
    /// </summary>
    TopNavVisibilityDescription,

    /// <summary>
    /// 当前状态不支持跳转
    /// </summary>
    CanNotSeek,

    /// <summary>
    /// 播放控制器显示方式
    /// </summary>
    MTCBehavior,

    /// <summary>
    /// 选择自动弹出（鼠标移动即显示）还是手动呼出（点击播放器才显示）
    /// </summary>
    MTCBehaviorDescription,

    /// <summary>
    /// 使用流式响应（打字机模式）
    /// </summary>
    UseStreamResponse,

    /// <summary>
    /// 如果你所使用的服务不支持流式响应，请关闭该选项
    /// </summary>
    UseStreamResponseDescription,

    /// <summary>
    /// Vulkan 硬解
    /// </summary>
    VulkanDecode,

    /// <summary>
    /// 岛（MPV）
    /// </summary>
    IslandPlayer,

    /// <summary>
    /// 自定义
    /// </summary>
    Custom,

    /// <summary>
    /// 自定义 MPV 配置
    /// </summary>
    CustomMpvConfig,

    /// <summary>
    /// MPV 用户请参考 mpv.io 的说明进行自定义配置
    /// </summary>
    CustomMpvConfigDescription,

    /// <summary>
    /// 使用网页播放器观看直播
    /// </summary>
    UseWebPlayerWhenLive,

    /// <summary>
    /// 如果本机观看直播体验不佳，请打开此选项在网页中观看
    /// </summary>
    UseWebPlayerWhenLiveDescription,

    /// <summary>
    /// 显示搜索推荐
    /// </summary>
    ShowSearchRecommend,

    /// <summary>
    /// 在顶部搜索框聚焦时提供搜索建议
    /// </summary>
    ShowSearchRecommendDescription,

    /// <summary>
    /// 尝试获取用户信息失败，这可能是网络原因，也有可能是你近期修改了密码，请重新登录或退出后重启应用
    /// </summary>
    LoginExpiredDescription,

    /// <summary>
    /// 登录失败
    /// </summary>
    LoginExpiredTitle,

    /// <summary>
    /// 重新登录
    /// </summary>
    ReSignIn,

    /// <summary>
    /// 文章评价
    /// </summary>
    ArticleEvaluation,

    /// <summary>
    /// 文章总结
    /// </summary>
    ArticleSummarize,

    /// <summary>
    /// 自定义文章评价提示词
    /// </summary>
    CustomArticleEvaluationDescription,

    /// <summary>
    /// 自定义文章总结提示词
    /// </summary>
    CustomArticleSummarizeDescription,

    /// <summary>
    /// 自定义提示词
    /// </summary>
    CustomPrompt,

    /// <summary>
    /// 创建自己的AI提示词
    /// </summary>
    CustomPromptDescription,

    /// <summary>
    /// 自定义视频评价提示词
    /// </summary>
    CustomVideoEvaluationDescription,

    /// <summary>
    /// 自定义视频总结提示词
    /// </summary>
    CustomVideoSummarizeDescription,

    /// <summary>
    /// 提示词
    /// </summary>
    Prompt,

    /// <summary>
    /// 提示词不能为空
    /// </summary>
    PromptCanNotBeEmpty,

    /// <summary>
    /// 提示词支持一些特定场景的变量：
    /// - {title} : 标题
    /// - {description} : 简介
    /// - {subtitle} : 视频字幕
    /// - {comments} : 热门评论
    /// </summary>
    PromptTip,

    /// <summary>
    /// 标题
    /// </summary>
    Title,

    /// <summary>
    /// 视频评价
    /// </summary>
    VideoEvaluation,

    /// <summary>
    /// 视频总结
    /// </summary>
    VideoSummarize,

    /// <summary>
    /// 复制标题
    /// </summary>
    CopyTitle,

    /// <summary>
    /// 侧边导航栏设置
    /// </summary>
    SideNavigationSetting,

    /// <summary>
    /// 开启或关闭导航区块
    /// </summary>
    SideNavigationSettingDescription,

    /// <summary>
    /// 章节 {0}
    /// </summary>
    ChapterIndexTemplate,

    /// <summary>
    /// 后退{0}秒
    /// </summary>
    BackwardTemplate,

    /// <summary>
    /// 前进{0}秒
    /// </summary>
    ForwardTemplate,

    /// <summary>
    /// 播放器错误
    /// </summary>
    MpvError,

    /// <summary>
    /// 尝试加载音频输出时发生错误，请查看日志以了解详情
    /// </summary>
    MpvErrorAudioFailed,

    /// <summary>
    /// MPV 暂不支持加载此光盘
    /// </summary>
    MpvErrorDiscInitFailed,

    /// <summary>
    /// 有些不明所以的错误发生了，请查看日志以了解详情
    /// </summary>
    MpvErrorGeneric,

    /// <summary>
    /// 尝试加载文件时发生错误，请查看日志以了解详情
    /// </summary>
    MpvErrorLoadingFailed,

    /// <summary>
    /// 没有多余的内存可供分配，换句话说，爆内存了，重启电脑试试
    /// </summary>
    MpvErrorNoMemory,

    /// <summary>
    /// 看上去没什么可供播放的内容
    /// </summary>
    MpvErrorNotingToPlay,

    /// <summary>
    /// 无法支持当前的音频直通格式
    /// </summary>
    MpvErrorPassthroughFormatUnsupported,

    /// <summary>
    /// MPV 初始化失败，可能是写了无法解析的配置，请查看日志以了解详情
    /// </summary>
    MpvErrorUninitialized,

    /// <summary>
    /// 未知格式，无法播放
    /// </summary>
    MpvErrorUnknownFormat,

    /// <summary>
    /// 由于某些原因，暂不支持播放
    /// </summary>
    MpvErrorUnsupported,

    /// <summary>
    /// 尝试加载视频输出时发生错误，请查看日志以了解详情
    /// </summary>
    MpvErrorVideoFailed,

    /// <summary>
    /// 进度跳转发生异常，无法建立和服务器的有效连接
    /// </summary>
    SeekFailed,

    /// <summary>
    /// 播放上一个：{0}
    /// </summary>
    PrevVideoTemplate,

    /// <summary>
    /// 播放下一个：{0}
    /// </summary>
    NextVideoTemplate,

    /// <summary>
    /// 还原黑边
    /// </summary>
    CancelCutBlackArea,

    /// <summary>
    /// 去除黑边
    /// </summary>
    CutBlackArea,

    /// <summary>
    /// 暂停
    /// </summary>
    Pause,

    /// <summary>
    /// 静音
    /// </summary>
    Mute,

    /// <summary>
    /// 取消静音
    /// </summary>
    Unmute,

    /// <summary>
    /// 连接中，请稍候...
    /// </summary>
    Connecting,

    /// <summary>
    /// 加载中，请稍候...
    /// </summary>
    Loading,

    /// <summary>
    /// 播放结束
    /// </summary>
    PlayEnd,

    /// <summary>
    /// 视频播放结束啦~
    /// </summary>
    PlayEndDescription,

    /// <summary>
    /// 播放速度
    /// </summary>
    PlaySpeed,

    /// <summary>
    /// 置顶窗口
    /// </summary>
    TopWindow,

    /// <summary>
    /// 字幕设置
    /// </summary>
    SubtitleSetting,

    /// <summary>
    /// 关闭窗口
    /// </summary>
    CloseWindow,

    /// <summary>
    /// 启用字幕
    /// </summary>
    SubtitleEnabled,

    /// <summary>
    /// 在当前播放窗口中启用字幕功能，关闭后将取消字幕显示（不会延续到下一个播放窗口）
    /// </summary>
    SubtitleEnabledDescription,

    /// <summary>
    /// 字幕位置
    /// </summary>
    SubtitlePosition,

    /// <summary>
    /// 横屏与竖屏使用不同的字幕位置配置，将根据当前窗口横纵比自动切换
    /// </summary>
    SubtitlePositionTip,

    /// <summary>
    /// 横屏
    /// </summary>
    HorizontalScreen,

    /// <summary>
    /// 竖屏
    /// </summary>
    VerticalScreen,

    /// <summary>
    /// 文本字幕字体
    /// </summary>
    SubtitleFontFamily,

    /// <summary>
    /// --sub-font，适用于文本字幕
    /// </summary>
    SubtitleFontFamilyDescription,

    /// <summary>
    /// 文本字幕字号
    /// </summary>
    SubtitleFontSize,

    /// <summary>
    /// --sub-font-size，适用于文本字幕
    /// </summary>
    SubtitleFontSizeDescription,

    /// <summary>
    /// 字幕延迟秒数
    /// </summary>
    SubtitleDelaySeconds,

    /// <summary>
    /// 正数为延迟，负数为提前
    /// </summary>
    SubtitleDelaySecondsDescription,

    /// <summary>
    /// 弹幕描边大小
    /// </summary>
    DanmakuOutlineSize,

    /// <summary>
    /// 弹幕刷新率
    /// </summary>
    DanmakuRefreshRate,

    /// <summary>
    /// 快速刷新
    /// </summary>
    QuickRefreshRate,

    /// <summary>
    /// 标准刷新
    /// </summary>
    StandardRefreshRate,

    /// <summary>
    /// 启用的弹幕类型
    /// </summary>
    EnabledDanmakuMode,

    /// <summary>
    /// 滚动
    /// </summary>
    RollingDanmaku,

    /// <summary>
    /// 已加载 {0} 条弹幕
    /// </summary>
    DanmakuCountTemplate,

    /// <summary>
    /// 无弹幕
    /// </summary>
    DanmakuEmpty,

    /// <summary>
    /// 下载音频
    /// </summary>
    DownloadAudio,

    /// <summary>
    /// 截图后行为
    /// </summary>
    ScreenshotPostBehavior,

    /// <summary>
    /// 截图后处理图片的方式
    /// </summary>
    ScreenshotPostBehaviorDescription,

    /// <summary>
    /// 截图设置
    /// </summary>
    ScreenshotSetting,

    /// <summary>
    /// 调整视频截图保存文件夹和截图后行为
    /// </summary>
    ScreenshotSettingDescription,

    /// <summary>
    /// 打开图片
    /// </summary>
    OpenImage,

    /// <summary>
    /// 未设置
    /// </summary>
    Unset,

    /// <summary>
    /// 选择文件夹
    /// </summary>
    PickFolder,

    /// <summary>
    /// 复制图片
    /// </summary>
    CopyImage,

    /// <summary>
    /// 内置 libmpv
    /// </summary>
    InternalLibMpv,

    /// <summary>
    /// 你可以在打开的编辑器中编辑配置文件来自定义播放体验，但由于应用使用 libmpv，故而部分配置（比如 OSD）并不会生效。
    /// </summary>
    FirstOpenMpvConfigTip,

    /// <summary>
    /// 清空本地图片缓存后，所有在线图片都会重新从服务端请求并再次缓存
    /// </summary>
    ClearCacheTip,

    /// <summary>
    /// 没有缓存
    /// </summary>
    NoCache,

    /// <summary>
    /// 播放时隐藏主窗口
    /// </summary>
    HideMainWindowOnPlay,

    /// <summary>
    /// 播放窗口的初始位置将与主窗口一致
    /// </summary>
    HideMainWindowOnPlayDescription,

    /// <summary>
    /// 使用单窗口一体化操作
    /// </summary>
    UseIntegrationBehavior,

    /// <summary>
    /// 仅单播放窗口时，关闭播放窗口视作关闭应用，点击返回按钮才显示主窗口
    /// </summary>
    UseIntegrationBehaviorDescription,

    /// <summary>
    /// 日志级别
    /// </summary>
    LogLevel,

    /// <summary>
    /// 选择记录日志的详细程度
    /// </summary>
    LogLevelDescription,

    /// <summary>
    /// 警告
    /// </summary>
    Warn,

    /// <summary>
    /// 错误
    /// </summary>
    Error,

    /// <summary>
    /// 信息
    /// </summary>
    Info,

    /// <summary>
    /// 全部
    /// </summary>
    Verb,

    /// <summary>
    /// MPV 附加设置
    /// </summary>
    MpvExtraSetting,

    /// <summary>
    /// 内置 MPV 的一些附加参数设置
    /// </summary>
    MpvExtraSettingDescription,

    /// <summary>
    /// 音频独占
    /// </summary>
    AudioExclusive,

    /// <summary>
    /// 声道布局
    /// </summary>
    AudioChannel,

    /// <summary>
    /// 内置配置切换
    /// </summary>
    BuiltInProfileSwitch,

    /// <summary>
    /// 快速
    /// </summary>
    Fast,

    /// <summary>
    /// 精确跳转选项
    /// </summary>
    HrSeekSetting,

    /// <summary>
    /// 最大缓冲大小（MB）
    /// </summary>
    MaxCacheSize,

    /// <summary>
    /// 最大缓冲秒数
    /// </summary>
    MaxCacheSeconds,

    /// <summary>
    /// 将缓存写入硬盘
    /// </summary>
    CacheOnDisk,

    /// <summary>
    /// 缓存文件夹
    /// </summary>
    CacheDirectory,

    /// <summary>
    /// 重新选择文件夹
    /// </summary>
    ReselectFolder,

    /// <summary>
    /// 恢复默认
    /// </summary>
    RestoreDefault,

    /// <summary>
    /// 最大音量
    /// </summary>
    MaxVolume,

    /// <summary>
    /// 图片缓存
    /// </summary>
    ImageCache,

    /// <summary>
    /// 查看或清除当前图片缓存
    /// </summary>
    ImageCacheDescription,

    /// <summary>
    /// 声道布局
    /// </summary>
    AudioChannelLayout,

    /// <summary>
    /// 自动
    /// </summary>
    Auto,

    /// <summary>
    /// D3D12 硬解
    /// </summary>
    D3D12Decode,

    /// <summary>
    /// 立体声
    /// </summary>
    Stereo,

    /// <summary>
    /// 单声道
    /// </summary>
    Mono,

    /// <summary>
    /// 跳进秒数
    /// </summary>
    StepForwardSeconds,

    /// <summary>
    /// 单次跳进的时长（秒）
    /// </summary>
    StepForwardSecondsDescription,

    /// <summary>
    /// 后退秒数
    /// </summary>
    StepBackwardSeconds,

    /// <summary>
    /// 单次后退的时长（秒）
    /// </summary>
    StepBackwardSecondsDescription,

    /// <summary>
    /// 临时播放倍速
    /// </summary>
    TemporaryPlaybackRate,

    /// <summary>
    /// 在播放界面长按屏幕或者长按方向键的临时倍速值
    /// </summary>
    TemporaryPlaybackRateDescription,

    /// <summary>
    /// 发送弹幕
    /// </summary>
    SendDanmaku,

    /// <summary>
    /// 弹幕渲染引擎
    /// </summary>
    DanmakuRenderer,

    /// <summary>
    /// 显示菜单
    /// </summary>
    ShowMenu,

    /// <summary>
    /// 滚动加速
    /// </summary>
    ScrollAccelerate,

    /// <summary>
    /// 在应用内单次滚动行数增加到12以提高应用内滚动速度
    /// </summary>
    ScrollAccelerateDescription,

    /// <summary>
    /// 适用于 D3D11 的视频输出显卡
    /// </summary>
    D3D11Adapter,

    /// <summary>
    /// 适用于 Vulkan 的视频输出显卡
    /// </summary>
    VulkanDevice,

    /// <summary>
    /// 着色器
    /// </summary>
    Shaders,

    /// <summary>
    /// A（高质量）
    /// </summary>
    Anime4KAHigh,

    /// <summary>
    /// B（高质量）
    /// </summary>
    Anime4KBHigh,

    /// <summary>
    /// C（高质量）
    /// </summary>
    Anime4KCHigh,

    /// <summary>
    /// A+A（高质量）
    /// </summary>
    Anime4KAAHigh,

    /// <summary>
    /// B+B（高质量）
    /// </summary>
    Anime4KBBHigh,

    /// <summary>
    /// C+A（高质量）
    /// </summary>
    Anime4KCAHigh,

    /// <summary>
    /// A（快速）
    /// </summary>
    Anime4KALow,

    /// <summary>
    /// B（快速）
    /// </summary>
    Anime4KBLow,

    /// <summary>
    /// C（快速）
    /// </summary>
    Anime4KCLow,

    /// <summary>
    /// A+A（快速）
    /// </summary>
    Anime4KAALow,

    /// <summary>
    /// B+B（快速）
    /// </summary>
    Anime4KBBLow,

    /// <summary>
    /// C+A（快速）
    /// </summary>
    Anime4KCALow,

    /// <summary>
    /// NVIDIA 超分辨率
    /// </summary>
    NvidiaVsr,

    /// <summary>
    /// 清除着色器
    /// </summary>
    ClearShaders,

    /// <summary>
    /// 最大后向缓冲大小（MB）
    /// </summary>
    MaxBackCacheSize,

}
